___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
z = np.arange(10,51)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
z = np.arange(10, 51, 2)
z

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
x =  np.arange(0, 8, dtype=float).reshape(4, 4)
print(x)

ValueError: cannot reshape array of size 8 into shape (4,4)

#### Create a 3x3 identity matrix

In [2]:
import numpy as np
array_2D=np.identity(3)
print(array_2D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [3]:
from numpy import random

x = random.randint(100)

print(x)

4


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [4]:
import numpy as np
rand_num = np.random.normal(0,1,25)
print(rand_num)

[ 1.78077997 -0.55969714 -0.67549078 -0.33478771 -1.011471   -1.12649834
 -0.05666006  1.01854332  1.3853555   1.03228954  0.24908184 -2.02483616
 -0.35288022  0.04857649  0.8151171  -0.34385341 -0.19908821 -0.00240983
  0.68567674 -0.74360156 -0.72138779  0.54082195 -0.83445702 -0.22803066
 -0.01825601]


#### Create the following matrix:

In [15]:
x = np.matrix(np.arange(100,dtype=float).reshape((10,10)));
x

matrix([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
        [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
        [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
        [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
        [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
        [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
        [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
        [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
x = np.matrix(np.arange(10).reshape(4, 5))

ValueError: cannot reshape array of size 10 into shape (4,5)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
mat = np.arange()

ValueError: cannot reshape array of size 14 into shape (3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

20

In [16]:
arr_2d = np.array([[2, 18, 3], [7, 6, 2], [12, 9, 2]])
arr_2d[:,:1]

array([[ 2],
       [ 7],
       [12]])

In [17]:
arr_2d[:,:1]

array([[ 2],
       [ 7],
       [12]])

In [18]:
arr = [[21, 22, 23, 24, 25]]
arr

[[21, 22, 23, 24, 25]]

In [19]:
arr = [[21, 22, 23, 24, 25]]
arr

[[21, 22, 23, 24, 25]]

In [22]:
arr = [21, 22, 23, 24, 25]
arr

[21, 22, 23, 24, 25]

### Now do the following

#### Get the sum of all the values in mat

In [81]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [82]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [84]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!